AWSTemplateFormatVersion: 2010-09-09
Metadata:
  DefaultName: store
  
Parameters:

  # Database Informations
  DatabaseEndpoint:
    Description: Database Server Endpoint
    Type: String
  DatabaseName:
    Description: Database Name
    Type: String
    Default: oh
  DatabasePort:
    Description: Database Name
    Type: String
    Default: 1443
  DatabaseUsername:
    Description: Database Server username
    Type: String
    Default: sqladmin
  DatabasePassword:
    Description: Database Server password
    Type: String
    NoEcho: 'True'
  # / Database Informations  

  # Application Configs and Secrets
  ApiUsername:
    Description: Api Username
    Type: String
  ApiPassword:
    Description: Api Password
    Type: String
    NoEcho: 'True'
  # / Application Configs and Secrets

  # Keys
  PpkKey:
    Description: Api Username
    Type: String
    NoEcho: 'True'
  SshKey:
    Description: Api Password
    Type: String
    NoEcho: 'True'
  # / Keys

Resources:
  #AWS::StackName construct doesn't seems to be working for localstack

  ApiAuthStore:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '${AWS::StackName}-ApiAuthStore'
      Description: Store ApiAuth Information
      SecretString: !Sub '{"user:${ApiUsername},key:${ApiPassword}"}'

  DatbaseStore:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '${AWS::StackName}-DatabaseStore'
      Description: Store Datbase Information
      SecretString: !Sub '{"dbendpoint:${DatabaseEndpoint},dbname:${DatabaseName},dbport:${DatabasePort},dbuser:${DatabaseUsername},dbpassword:${DatabasePassword}"}'

  PgpKeyStore:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '${AWS::StackName}-PgpKeyStore'
      Description: For Storing PpkKey 
      SecretString: !Ref PpkKey

  SshKeyStore:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '${AWS::StackName}-SshKeyStore'
      Description: Fore Storing SshKey
      SecretString: !Ref SshKey

  StoresPolicies:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: ["secretsmanager:Describe*","secretsmanager:Get*","secretsmanager:List*"]
            Resource: [!Ref SshKeyStore, !Ref PgpKeyStore, !Ref DatbaseStore, !Ref ApiAuthStore]

